openapi: 3.2.0
info:
  title: Webhooks Loan Application Webhooks API
  description: API for interacting with account assignment webhooks, document webhooks, job webhooks, loan application webhooks, loan milestone webhooks, loan officer webhooks, loan webhooks, milestone webhooks, organization webhooks, state license webhooks, subscriptions, user webhooks, verification webhooks, and webhooks in the nCino Mortgage system
  version: '1.0'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://api.ncinomortgage.com
  description: Production server
security:
- OAuth2: []
tags:
- name: Loan Application Webhooks
  description: Webhook events pertaining to loan applications
paths: {}
webhooks:
  loan_app_abandoned:
    post:
      tags:
      - Loan Application Webhooks
      operationId: loan_application_webhooks-loan_app_abandoned
      responses:
        '200':
          $ref: '#/components/responses/WebhookResponse'
      description: A <<glossary:webhook>> notification sent out when a <<glossary:loan application>> is abandoned.
      summary: loan_app_abandoned
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
            example:
              _id: 00000000-0000-0000-0000-000000000000
              _timestamp: '1989-08-23T00:00:00+00:00'
              events:
              - _id: 00000000-0000-0000-0000-000000000000
                _timestamp: '1989-08-23T00:00:00+00:00'
                _links:
                  loan_application: /fake/path/to/loan_application
                event: loan_app_abandoned
                event_info:
                  borrower_name: Borrower name
  loan_app_imported:
    post:
      tags:
      - Loan Application Webhooks
      operationId: loan_application_webhooks-loan_app_imported
      responses:
        '200':
          $ref: '#/components/responses/WebhookResponse'
      description: A <<glossary:webhook>> notification sent out when a <<glossary:loan application>> is imported.
      summary: loan_app_imported
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
            example:
              _id: 00000000-0000-0000-0000-000000000000
              _timestamp: '1989-08-23T00:00:00+00:00'
              events:
              - _id: 00000000-0000-0000-0000-000000000000
                _timestamp: '1989-08-23T00:00:00+00:00'
                _links:
                  loan_application: /fake/path/to/loan_application
                event: loan_app_imported
                event_info:
                  borrower_name: Borrower name
  loan_app_started:
    post:
      tags:
      - Loan Application Webhooks
      operationId: loan_application_webhooks-loan_app_started
      responses:
        '200':
          $ref: '#/components/responses/WebhookResponse'
      description: A <<glossary:webhook>> notification sent out when a <<glossary:loan application>> is started.
      summary: loan_app_started
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
            example:
              _id: 00000000-0000-0000-0000-000000000000
              _timestamp: '1989-08-23T00:00:00+00:00'
              events:
              - _id: 00000000-0000-0000-0000-000000000000
                _timestamp: '1989-08-23T00:00:00+00:00'
                _links:
                  loan_application: /fake/path/to/loan_application
                event: loan_app_started
                event_info:
                  borrower_name: Borrower name
  loan_app_submitted:
    post:
      tags:
      - Loan Application Webhooks
      operationId: loan_application_webhooks-loan_app_submitted
      responses:
        '200':
          $ref: '#/components/responses/WebhookResponse'
      description: A <<glossary:webhook>> notification sent out when a <<glossary:loan application>> is submitted.
      summary: loan_app_submitted
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
            example:
              _id: 00000000-0000-0000-0000-000000000000
              _timestamp: '1989-08-23T00:00:00+00:00'
              events:
              - _id: 00000000-0000-0000-0000-000000000000
                _timestamp: '1989-08-23T00:00:00+00:00'
                _links:
                  loan_application: /fake/path/to/loan_application
                event: loan_app_submitted
                event_info:
                  borrower_name: Borrower name
  loan_app_updated:
    post:
      tags:
      - Loan Application Webhooks
      operationId: loan_application_webhooks-loan_app_updated
      responses:
        '200':
          $ref: '#/components/responses/WebhookResponse'
      description: A <<glossary:webhook>> notification sent out when a <<glossary:loan application>> is updated.
      summary: loan_app_updated
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
            example:
              _id: 00000000-0000-0000-0000-000000000000
              _timestamp: '1989-08-23T00:00:00+00:00'
              events:
              - _id: 00000000-0000-0000-0000-000000000000
                _timestamp: '1989-08-23T00:00:00+00:00'
                _links:
                  loan_application: /fake/path/to/loan_application
                event: loan_app_updated
                event_info:
                  borrower_name: Borrower name
components:
  schemas:
    OrganizationCreatedEventInfo:
      type: object
      properties:
        org_type:
          type: string
          enum:
          - REGION
          - BRANCH
          description: Type of organization (REGION or BRANCH).
        name:
          type: string
          description: Name of the organization created.
      required:
      - org_type
      - name
      description: The event info particular to the organization_created event.
    LoanAppSubmittedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_application:
                type: string
            required:
            - loan_application
            example:
              loan_application: /fake/path/to/loan_application
          event:
            type: string
            enum:
            - loan_app_submitted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanApplicationEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    MilestoneDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              milestones:
                type: string
            required:
            - milestones
            example:
              milestones: /fake/path/to/milestones
          event:
            type: string
            enum:
            - milestone_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/MilestoneDeletedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserDeletedEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      description: The event info particular to the user_deleted event.
    LoanOfficerDemotedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_officer:
                type: string
            required:
            - loan_officer
            example:
              loan_officer: /fake/path/to/loan_officer
          event:
            type: string
            enum:
            - loan_officer_demoted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanOfficerAdminChangeEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserEnabledEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      description: The event info particular to the user_enabled event.
    LoanAppStartedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_application:
                type: string
            required:
            - loan_application
            example:
              loan_application: /fake/path/to/loan_application
          event:
            type: string
            enum:
            - loan_app_started
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanApplicationEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanOfficerAdminChangeEventInfo:
      type: object
      properties:
        admin_type:
          type: string
          enum:
          - COMPANY_ADMIN
          - REGION_ADMIN
          - BRANCH_ADMIN
          description: Type of admin to which the loan officer was promoted or from which the loan officer was demoted.
        name:
          type: string
          description: Name of the loan officer.
      required:
      - admin_type
      - name
      description: The event info particular to the loan_officer_promoted and loan_officer_demoted events.
    LoanAppAbandonedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_application:
                type: string
            required:
            - loan_application
            example:
              loan_application: /fake/path/to/loan_application
          event:
            type: string
            enum:
            - loan_app_abandoned
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanApplicationEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserFirstLoginEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      description: The event info particular to the user_first_login event.
    StateLicenseDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              state_licenses:
                type: string
            required:
            - state_licenses
            example:
              state_licenses: /fake/path/to/state_licenses
          event:
            type: string
            enum:
            - state_license_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/StateLicenseEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - loan_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    OrganizationCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              organization:
                type: string
            required:
            - organization
            example:
              organization: /fake/path/to/organization
          event:
            type: string
            enum:
            - organization_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/OrganizationCreatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    WebhookRequestBody:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          events:
            type: array
            items:
              $ref: '#/components/schemas/WebhookRequestEvent'
            minItems: 1
            description: An array of events that have been triggered.
        required:
        - events
        additionalProperties: false
    DocumentUpdatedEventInfo:
      type: object
      properties:
        document_name:
          type: string
          description: Name of the updated document.
        doc_type:
          type: string
          description: Document type classification.
          nullable: true
        task_name:
          type: string
          description: Name of the associated task.
          nullable: true
        loan_number:
          type: string
          description: Loan number.
          nullable: true
      required:
      - document_name
      description: The event info for the document_updated event.
    UserUpdatedEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      description: The event info particular to the user_updated event.
    AccountAssignmentEventInfo:
      type: object
      properties:
        assignee_type:
          type: string
          description: Type of the account that owns the assignment.
        assignee_name:
          type: string
          description: Name of the account that owns the assignment.
        assignor_type:
          type: string
          description: Type of entity the relevant account has access to.
        assignor_name:
          type: string
          description: Name of the entity the relevant account has access to.
      required:
      - assignee_type
      - assignee_name
      - assignor_type
      - assignor_name
      description: The event info particular to the account assignment events.
    LoanApplicationEventInfo:
      type: object
      properties:
        borrower_name:
          type: string
          description: Borrower name.
      description: The event info particular to the loan application webhook group events.
    WebhookRequestEvent:
      type: object
      properties: {}
      discriminator:
        propertyName: event
        mapping:
          job_status_changed: '#/components/schemas/JobStatusChangedWebhookRequestBody0'
          loan_app_started: '#/components/schemas/LoanAppStartedWebhookRequestBody0'
          loan_app_updated: '#/components/schemas/LoanAppUpdatedWebhookRequestBody0'
          loan_app_submitted: '#/components/schemas/LoanAppSubmittedWebhookRequestBody0'
          loan_app_imported: '#/components/schemas/LoanAppImportedWebhookRequestBody0'
          loan_app_abandoned: '#/components/schemas/LoanAppAbandonedWebhookRequestBody0'
          document_uploaded: '#/components/schemas/DocumentUploadedWebhookRequestBody0'
          document_created: '#/components/schemas/DocumentCreatedWebhookRequestBody0'
          document_updated: '#/components/schemas/DocumentUpdatedWebhookRequestBody0'
          loan_milestone_updated: '#/components/schemas/LoanMilestoneUpdatedWebhookRequestBody0'
          loan_milestone_completed: '#/components/schemas/LoanMilestoneCompletedWebhookRequestBody0'
          loan_created: '#/components/schemas/LoanCreatedWebhookRequestBody0'
          loan_updated: '#/components/schemas/LoanUpdatedWebhookRequestBody0'
          loan_deleted: '#/components/schemas/LoanDeletedWebhookRequestBody0'
          loan_activated: '#/components/schemas/LoanActivatedWebhookRequestBody0'
          loan_deactivated: '#/components/schemas/LoanDeactivatedWebhookRequestBody0'
          milestones_reordered: '#/components/schemas/MilestonesReorderedWebhookRequestBody0'
          milestone_created: '#/components/schemas/MilestoneCreatedWebhookRequestBody0'
          milestone_deleted: '#/components/schemas/MilestoneDeletedWebhookRequestBody0'
          organization_created: '#/components/schemas/OrganizationCreatedWebhookRequestBody0'
          organization_deleted: '#/components/schemas/OrganizationDeletedWebhookRequestBody0'
          state_license_created: '#/components/schemas/StateLicenseCreatedWebhookRequestBody0'
          state_license_updated: '#/components/schemas/StateLicenseUpdatedWebhookRequestBody0'
          state_license_deleted: '#/components/schemas/StateLicenseDeletedWebhookRequestBody0'
          account_assignment_created: '#/components/schemas/AccountAssignmentCreatedWebhookRequestBody0'
          account_assignment_deleted: '#/components/schemas/AccountAssignmentDeletedWebhookRequestBody0'
          loan_officer_promoted: '#/components/schemas/LoanOfficerPromotedWebhookRequestBody0'
          loan_officer_demoted: '#/components/schemas/LoanOfficerDemotedWebhookRequestBody0'
          user_created: '#/components/schemas/UserCreatedWebhookRequestBody0'
          user_updated: '#/components/schemas/UserUpdatedWebhookRequestBody0'
          user_enabled: '#/components/schemas/UserEnabledWebhookRequestBody0'
          user_disabled: '#/components/schemas/UserDisabledWebhookRequestBody0'
          user_first_login: '#/components/schemas/UserFirstLoginWebhookRequestBody0'
          user_deleted: '#/components/schemas/UserDeletedWebhookRequestBody0'
          verification_available: '#/components/schemas/VerificationAvailableWebhookRequestBody0'
      oneOf:
      - $ref: '#/components/schemas/JobStatusChangedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanAppStartedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanAppUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanAppSubmittedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanAppImportedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanAppAbandonedWebhookRequestBody0'
      - $ref: '#/components/schemas/DocumentUploadedWebhookRequestBody0'
      - $ref: '#/components/schemas/DocumentCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/DocumentUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanMilestoneUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanMilestoneCompletedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanActivatedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanDeactivatedWebhookRequestBody0'
      - $ref: '#/components/schemas/MilestonesReorderedWebhookRequestBody0'
      - $ref: '#/components/schemas/MilestoneCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/MilestoneDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/OrganizationCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/OrganizationDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/StateLicenseCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/StateLicenseUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/StateLicenseDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/AccountAssignmentCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/AccountAssignmentDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanOfficerPromotedWebhookRequestBody0'
      - $ref: '#/components/schemas/LoanOfficerDemotedWebhookRequestBody0'
      - $ref: '#/components/schemas/UserCreatedWebhookRequestBody0'
      - $ref: '#/components/schemas/UserUpdatedWebhookRequestBody0'
      - $ref: '#/components/schemas/UserEnabledWebhookRequestBody0'
      - $ref: '#/components/schemas/UserDisabledWebhookRequestBody0'
      - $ref: '#/components/schemas/UserFirstLoginWebhookRequestBody0'
      - $ref: '#/components/schemas/UserDeletedWebhookRequestBody0'
      - $ref: '#/components/schemas/VerificationAvailableWebhookRequestBody0'
      additionalProperties: false
    UserCreatedEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      - type: object
        properties:
          user_borrower:
            type: string
            description: Borrower's name.
      description: The event info particular to the user_created event.
    JobType:
      type: string
      enum:
      - SYNC_LOAN_APPS
      - VALIDATE_WEBHOOK_URL
      - GENERATE_ORGANIZATION_REPORT
      - DELETE_REGION_BRANCH
      - ORDER_VERIFICATION_REPORT
      - REFRESH_VERIFICATION_REPORTS
      - DISCONNECT_BORROWER
      - SEND_VERIFICATION_REMINDER
      - DELETE_LOAN
      - REASSIGN_BORROWERS_PARTNERS_LOAN_APPS
    UserEnabledWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              user:
                type: string
            required:
            - user
            example:
              user: /fake/path/to/user
          event:
            type: string
            enum:
            - user_enabled
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserEnabledEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanMilestoneCompletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_milestone:
                type: string
            required:
            - loan_milestone
            example:
              loan_milestone: /fake/path/to/loan_milestone
          event:
            type: string
            enum:
            - loan_milestone_completed
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanMilestoneCompletedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserDisabledEventInfo:
      allOf:
      - $ref: '#/components/schemas/UserEventInfo'
      description: The event info particular to the user_disabled event.
    LoanDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loans:
                type: string
            required:
            - loans
            example:
              loans: /fake/path/to/loans
          event:
            type: string
            enum:
            - loan_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanOfficerPromotedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_officer:
                type: string
            required:
            - loan_officer
            example:
              loan_officer: /fake/path/to/loan_officer
          event:
            type: string
            enum:
            - loan_officer_promoted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanOfficerAdminChangeEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    StateLicenseEventInfo:
      type: object
      properties:
        state:
          oneOf:
          - $ref: '#/components/schemas/StateCode'
          - $ref: '#/components/schemas/NationwideCode'
          description: State license's state.
      required:
      - state
      description: The event info particular to the state license events.
    MilestoneCreatedEventInfo:
      type: object
      properties:
        name:
          type: string
          description: Name of the milestone.
      required:
      - name
      description: The event info particular to the milestone_created event.
    LoanMilestoneUpdatedEventInfo:
      type: object
      properties:
        milestone_name:
          type: string
          description: Name of the milestone.
        status:
          type: string
          description: Current status of the milestone.
        loan_number:
          type: string
          description: Loan number.
      required:
      - milestone_name
      - status
      - loan_number
      description: The event info for the loan_milestone_updated event.
    LoanAppUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_application:
                type: string
            required:
            - loan_application
            example:
              loan_application: /fake/path/to/loan_application
          event:
            type: string
            enum:
            - loan_app_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanApplicationEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              user:
                type: string
            required:
            - user
            example:
              user: /fake/path/to/user
          event:
            type: string
            enum:
            - user_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserUpdatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    VerificationReportType:
      type: string
      enum:
      - BOTH
      - DOC_VOI_MORTGAGE
      - DVOE
      - VOA
      - VOAI
      - VOA_HISTORY
      - VOE
      - VOE_MORTGAGE
      - VOE_PAYROLL
      - VOE_TRANSACTIONS
      - VOI
      - VOIE
      - VOIE_MORTGAGE
      - VOIE_PAYROLL
      - VOIE_TX_VERIFY
      description: Types of verification reports.
    VerificationAvailableEventInfo:
      type: object
      properties:
        report_type:
          allOf:
          - $ref: '#/components/schemas/VerificationReportType'
          description: Type of the report that is available.
      required:
      - report_type
      description: The event info particular to the verification_complete event.
    OrganizationDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              parent_organization:
                type: string
            required:
            - parent_organization
            example:
              parent_organization: /fake/path/to/parent_organization
          event:
            type: string
            enum:
            - organization_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/OrganizationDeletedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    DocumentUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - document_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/DocumentUpdatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    JobStatusChangedEventInfo:
      type: object
      properties:
        job_type:
          allOf:
          - $ref: '#/components/schemas/JobType'
          description: Type of job that was changed.
        job_description:
          type: string
          description: Job's description.
          nullable: true
        from_status:
          allOf:
          - $ref: '#/components/schemas/NullableJobStatus'
          description: Job's status prior to the change. If the job was just created, this will be nil.
        to_status:
          allOf:
          - $ref: '#/components/schemas/JobStatus'
          description: Job's status after the change.
        changed_at:
          type: string
          format: date-time
          description: When the job's status changed.
      description: The event info particular to the job_status_changed event.
    NullableJobStatus:
      type: string
      enum:
      - QUEUED
      - STARTED
      - QUEUED_FOR_RETRY
      - COMPLETED
      - FAILED
      - null
      nullable: true
    UserCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              user:
                type: string
            required:
            - user
            example:
              user: /fake/path/to/user
          event:
            type: string
            enum:
            - user_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserCreatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    MilestoneCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              milestone:
                type: string
            required:
            - milestone
            example:
              milestone: /fake/path/to/milestone
          event:
            type: string
            enum:
            - milestone_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/MilestoneCreatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    MilestoneDeletedEventInfo:
      type: object
      properties:
        name:
          type: string
          description: Name of the organization.
      required:
      - name
      description: The event info particular to the milestone_deleted event.
    LoanCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - loan_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    JobStatus:
      type: string
      enum:
      - QUEUED
      - STARTED
      - QUEUED_FOR_RETRY
      - COMPLETED
      - FAILED
    LoanAppImportedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_application:
                type: string
            required:
            - loan_application
            example:
              loan_application: /fake/path/to/loan_application
          event:
            type: string
            enum:
            - loan_app_imported
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanApplicationEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    NationwideCode:
      type: string
      enum:
      - US
      description: Nationwide code.
    LoanMilestoneUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_milestone:
                type: string
            required:
            - loan_milestone
            example:
              loan_milestone: /fake/path/to/loan_milestone
          event:
            type: string
            enum:
            - loan_milestone_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanMilestoneUpdatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserFirstLoginWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              user:
                type: string
            required:
            - user
            example:
              user: /fake/path/to/user
          event:
            type: string
            enum:
            - user_first_login
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserFirstLoginEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    DocumentCreatedEventInfo:
      type: object
      properties:
        document_name:
          type: string
          description: Name of the created document.
        doc_type:
          type: string
          description: Document type classification.
          nullable: true
        task_name:
          type: string
          description: Name of the associated task.
          nullable: true
        loan_number:
          type: string
          description: Loan number.
          nullable: true
      required:
      - document_name
      description: The event info for the document_created event.
    UserDisabledWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              user:
                type: string
            required:
            - user
            example:
              user: /fake/path/to/user
          event:
            type: string
            enum:
            - user_disabled
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserDisabledEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    StateLicenseUpdatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              state_license:
                type: string
            required:
            - state_license
            example:
              state_license: /fake/path/to/state_license
          event:
            type: string
            enum:
            - state_license_updated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/StateLicenseEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    BaseWebhookRequestBody:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          description: Unique identifier for the webhook event.
          example: 00000000-0000-0000-0000-000000000000
        _timestamp:
          type: string
          format: date-time
          description: Timestamp for when the webhook event was triggered.
          example: '1989-08-23T00:00:00+00:00'
      required:
      - _id
      - _timestamp
      additionalProperties: false
    DocumentUploadedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - document_uploaded
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/DocumentUploadedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserEventInfo:
      type: object
      properties:
        name:
          type: string
          description: Name of user.
        user_type:
          type: string
          enum:
          - USER_BORROWER
          - COMPANY_ADMIN
          - REGION_ADMIN
          - BRANCH_ADMIN
          - LOAN_OFFICER
          - TEAM_MEMBER
          - PARTNER
          description: Type of user.
      description: The event info shared between user events.
    AccountAssignmentDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              assignments:
                type: string
            required:
            - assignments
            example:
              assignments: /fake/path/to/assignments
          event:
            type: string
            enum:
            - account_assignment_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/AccountAssignmentEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    UserDeletedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan_officer:
                type: string
            required:
            - loan_officer
            example:
              loan_officer: /fake/path/to/loan_officer
          event:
            type: string
            enum:
            - user_deleted
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/UserDeletedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    MilestonesReorderedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              milestones:
                type: string
            required:
            - milestones
            example:
              milestones: /fake/path/to/milestones
          event:
            type: string
            enum:
            - milestones_reordered
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/MilestonesReorderedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    OrganizationDeletedEventInfo:
      type: object
      properties:
        org_type:
          type: string
          enum:
          - REGION
          - BRANCH
          description: Type of organization (REGION or BRANCH).
        name:
          type: string
          description: Name of the organization deleted.
      required:
      - org_type
      - name
      description: The event info particular to the organization_deleted event
    LoanMilestoneCompletedEventInfo:
      type: object
      properties:
        milestone_name:
          type: string
          description: Name of the milestone.
        loan_number:
          type: string
          description: Loan number.
      required:
      - milestone_name
      - loan_number
      description: The event info for the loan_milestone_completed event.
    JobStatusChangedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              job:
                type: string
            required:
            - job
            example:
              job: /fake/path/to/job
          event:
            type: string
            enum:
            - job_status_changed
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/JobStatusChangedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanDeactivatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - loan_deactivated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    MilestonesReorderedEventInfo:
      type: object
      properties:
        name:
          type: string
          description: Name of the organization.
      required:
      - name
      description: The event info particular to the milestones_reordered event.
    DocumentCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - document_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/DocumentCreatedEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    AccountAssignmentCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              assignment:
                type: string
            required:
            - assignment
            example:
              assignment: /fake/path/to/assignment
          event:
            type: string
            enum:
            - account_assignment_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/AccountAssignmentEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    StateLicenseCreatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              state_license:
                type: string
            required:
            - state_license
            example:
              state_license: /fake/path/to/state_license
          event:
            type: string
            enum:
            - state_license_created
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/StateLicenseEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanActivatedWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              loan:
                type: string
            required:
            - loan
            example:
              loan: /fake/path/to/loan
          event:
            type: string
            enum:
            - loan_activated
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/LoanEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    LoanEventInfo:
      type: object
      properties:
        loan_number:
          type: string
          description: Loan number.
      required:
      - loan_number
      description: The event info particular to the loan webhook group events.
    VerificationAvailableWebhookRequestBody0:
      allOf:
      - $ref: '#/components/schemas/BaseWebhookRequestBody'
      - type: object
        properties:
          _links:
            type: object
            properties:
              verification:
                type: string
            required:
            - verification
            example:
              verification: /fake/path/to/verification
          event:
            type: string
            enum:
            - verification_available
            description: Event that triggered the webhook.
          event_info:
            allOf:
            - $ref: '#/components/schemas/VerificationAvailableEventInfo'
        required:
        - _links
        - event
        - event_info
        additionalProperties: false
    DocumentUploadedEventInfo:
      type: object
      properties:
        document_name:
          type: string
          description: Name of the uploaded document.
        doc_type:
          type: string
          description: Document type classification.
          nullable: true
        task_name:
          type: string
          description: Name of the associated task.
          nullable: true
        loan_number:
          type: string
          description: Loan number.
          nullable: true
        uploaded_by:
          type: string
          description: Who uploaded the document (borrower or servicer).
      required:
      - document_name
      - uploaded_by
      description: The event info for the document_uploaded event.
    StateCode:
      type: string
      enum:
      - AA
      - AE
      - AK
      - AL
      - AP
      - AR
      - AS
      - AZ
      - CA
      - CO
      - CT
      - DC
      - DE
      - FL
      - FM
      - GA
      - GU
      - HI
      - IA
      - ID
      - IL
      - IN
      - KS
      - KY
      - LA
      - MA
      - MD
      - ME
      - MH
      - MI
      - MN
      - MO
      - MP
      - MS
      - MT
      - NC
      - ND
      - NE
      - NH
      - NJ
      - NM
      - NV
      - NY
      - OH
      - OK
      - OR
      - PA
      - PR
      - PW
      - RI
      - SC
      - SD
      - TN
      - TX
      - UT
      - VA
      - VI
      - VT
      - WA
      - WI
      - WV
      - WY
      description: State abbreviated code.
  responses:
    WebhookResponse:
      description: Return a 200 status to indicate that the data was received successfully
      content: {}
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth 2.0 Access Token (Default)
      flows:
        clientCredentials:
          tokenUrl: /oauth/token
          scopes: {}
